#!/bin/bash -e

[[ $DEBUG == true ]] && set -x

if [[ $OSTYPE =~ ^darwin ]]; then
  # This is the GNU coreutils binary installed with
  # brew install coreutils
  # brew namespaces them under g* symlinks
  cmd=`which greadlink`
elif [[ $OSTYPE =~ ^linux ]]; then
  cmd=`which readlink`
else
  echo Unsopported platform $OSTYPE
  exit 1
fi

dotfiles_dir=$($cmd -f `dirname $0`)
echo Going to setup dotfiles from $dotfiles_dir

ln -s $dotfiles_dir/.bashrc ~/
ln -s $dotfiles_dir/.bash_profile ~/

ln -s $dotfiles_dir/.tmux ~/
ln -s $dotfiles_dir/.tmux.conf ~/
